# Generated by Django 5.2 on 2025-05-07 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_course_category_alter_enroll_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='course',
        ),
        migrations.AddField(
            model_name='cart',
            name='courses',
            field=models.ManyToManyField(related_name='cart_course', to='courses.course'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_course', to='courses.cart'),
        ),
        migrations.AlterField(
            model_name='course',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='course_images'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lessons', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CartContent',
        ),
    ]
