# Generated by Django 5.2 on 2025-05-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_payment_course_cart_courses_payment_cart_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
