# Generated by Django 5.2 on 2025-05-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='course',
            new_name='courses',
        ),
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together={('student', 'courses')},
        ),
    ]
