# Generated by Django 5.2 on 2025-05-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_rename_course_enroll_courses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='commet_header',
            new_name='comment_header',
        ),
    ]
