# Generated by Django 5.2 on 2025-05-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_rename_commet_header_review_comment_header'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewlike',
            unique_together=set(),
        ),
    ]
