# Generated by Django 5.2 on 2025-05-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_reviewlike_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewlike',
            unique_together={('review', 'student')},
        ),
    ]
