# Generated by Django 5.2 on 2025-05-11 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_reviewlike_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='course',
        ),
        migrations.AddField(
            model_name='favourite',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fav_course', to='courses.course'),
        ),
    ]
