# Generated by Django 5.2 on 2025-05-11 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_remove_favourite_course_favourite_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_course', to='courses.course'),
        ),
    ]
