# Generated by Django 5.2 on 2025-05-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_favourite_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('course', 'student')},
        ),
    ]
