# Generated by Django 5.2 on 2025-05-12 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together=set(),
        ),
    ]
